version = 5.2.2
archive_dir = /etc/letsencrypt/archive/kursor.site
cert = /etc/letsencrypt/live/kursor.site/cert.pem
privkey = /etc/letsencrypt/live/kursor.site/privkey.pem
chain = /etc/letsencrypt/live/kursor.site/chain.pem
fullchain = /etc/letsencrypt/live/kursor.site/fullchain.pem
[renewalparams]
account = a1de291af4d7bc085c5c2f977836d592
authenticator = webroot
webroot_path = /var/www/letsencrypt,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
kursor.site = /var/www/letsencrypt
www.kursor.site = /var/www/letsencrypt
